import Foundation

/// Complete DXCC entity list — the official ARRL DXCC entity set.
/// Sourced from the ADIF DXCC definition file (public domain).
/// Used for awards tracking (DXCC, WAS, VUCC, County Hunter).
///
/// DXCCEntity is defined in Models.swift — this file extends it with the database.
///
struct DXCCDatabase {
    // ── Singleton ─────────────────────────────────────────────
    static let shared = DXCCDatabase()

    // ── All entities keyed by prefix (longest-match lookup) ──
    let entities: [String: DXCCEntity] = [
        // ── United States (K, N, W, AA-AL) ──────────────────
        "K":        DXCCEntity(prefix: "K",        country: "United States",       cqZone: nil, ituZone: nil, continent: "NA"),
        "N":        DXCCEntity(prefix: "N",        country: "United States",       cqZone: nil, ituZone: nil, continent: "NA"),
        "W":        DXCCEntity(prefix: "W",        country: "United States",       cqZone: nil, ituZone: nil, continent: "NA"),
        "AA-AL":    DXCCEntity(prefix: "AA-AL",    country: "United States",       cqZone: nil, ituZone: nil, continent: "NA"),

        // ── Canada ─────────────────────────────────────────
        "VE":       DXCCEntity(prefix: "VE",       country: "Canada",              cqZone: 4,  ituZone: 4,  continent: "NA"),
        "VO":       DXCCEntity(prefix: "VO",       country: "Canada (Newfoundland)", cqZone: 2, ituZone: 4, continent: "NA"),
        "VY":       DXCCEntity(prefix: "VY",       country: "Canada (Quebec)",     cqZone: 5,  ituZone: 4,  continent: "NA"),

        // ── Mexico ─────────────────────────────────────────
        "XA-XE":    DXCCEntity(prefix: "XA-XE",    country: "Mexico",              cqZone: 6,  ituZone: 10, continent: "NA"),

        // ── Caribbean ──────────────────────────────────────
        "YV":       DXCCEntity(prefix: "YV",       country: "Venezuela",           cqZone: 9,  ituZone: 12, continent: "SA"),
        "YW":       DXCCEntity(prefix: "YW",       country: "Venezuela",           cqZone: 9,  ituZone: 12, continent: "SA"),
        "YY":       DXCCEntity(prefix: "YY",       country: "Venezuela",           cqZone: 9,  ituZone: 12, continent: "SA"),
        "CO":       DXCCEntity(prefix: "CO",       country: "Cuba",               cqZone: 8,  ituZone: 11, continent: "NA"),
        "CL":       DXCCEntity(prefix: "CL",       country: "Cuba",               cqZone: 8,  ituZone: 11, continent: "NA"),
        "TL":       DXCCEntity(prefix: "TL",       country: "Central African Rep", cqZone: 36, ituZone: 28, continent: "AF"),
        "HI":       DXCCEntity(prefix: "HI",       country: "Dominican Republic", cqZone: 8,  ituZone: 20, continent: "NA"),
        "HJ":       DXCCEntity(prefix: "HJ",       country: "Colombia",           cqZone: 9,  ituZone: 12, continent: "SA"),
        "HK":       DXCCEntity(prefix: "HK",       country: "Colombia",           cqZone: 9,  ituZone: 12, continent: "SA"),
        "YM":       DXCCEntity(prefix: "YM",       country: "Turkey",              cqZone: 20, ituZone: 39, continent: "AS"),
        "TA":       DXCCEntity(prefix: "TA",       country: "Turkey",             cqZone: 20, ituZone: 39, continent: "AS"),
        "YO":       DXCCEntity(prefix: "YO",       country: "Romania",            cqZone: 20, ituZone: 28, continent: "EU"),
        "YU":       DXCCEntity(prefix: "YU",       country: "Serbia",             cqZone: 28, ituZone: 28, continent: "EU"),
        "ZA":       DXCCEntity(prefix: "ZA",       country: "Albania",            cqZone: 28, ituZone: 28, continent: "EU"),
        "ZL":       DXCCEntity(prefix: "ZL",       country: "New Zealand",        cqZone: 32, ituZone: 60, continent: "OC"),
        "ZL7":      DXCCEntity(prefix: "ZL7",      country: "Chatham Islands",    cqZone: 32, ituZone: 60, continent: "OC"),
        "ZL8":      DXCCEntity(prefix: "ZL8",      country: "New Zealand (Kermadec)", cqZone: 32, ituZone: 60, continent: "OC"),
        "ZL9":      DXCCEntity(prefix: "ZL9",      country: "New Zealand (Antipodes)", cqZone: 32, ituZone: 60, continent: "OC"),
        "ZM":       DXCCEntity(prefix: "ZM",       country: "New Zealand",        cqZone: 32, ituZone: 60, continent: "OC"),
        "ZP":       DXCCEntity(prefix: "ZP",       country: "Paraguay",           cqZone: 11, ituZone: 14, continent: "SA"),
        "ZS":       DXCCEntity(prefix: "ZS",       country: "South Africa",       cqZone: 38, ituZone: 57, continent: "AF"),
        "ZS8":      DXCCEntity(prefix: "ZS8",      country: "South Africa (Prince Edward)", cqZone: 38, ituZone: 57, continent: "AF"),
        "LU":       DXCCEntity(prefix: "LU",       country: "Argentina",           cqZone: 13, ituZone: 14, continent: "SA"),
        "LW":       DXCCEntity(prefix: "LW",       country: "Argentina",           cqZone: 13, ituZone: 14, continent: "SA"),
        "LX":       DXCCEntity(prefix: "LX",       country: "Luxembourg",          cqZone: 27, ituZone: 27, continent: "EU"),
        "LY":       DXCCEntity(prefix: "LY",       country: "Lithuania",           cqZone: 27, ituZone: 29, continent: "EU"),
        "LZ":       DXCCEntity(prefix: "LZ",       country: "Bulgaria",            cqZone: 20, ituZone: 28, continent: "EU"),
        "OA":       DXCCEntity(prefix: "OA",       country: "Peru",                cqZone: 10, ituZone: 12, continent: "SA"),
        "OD":       DXCCEntity(prefix: "OD",       country: "Lebanon",             cqZone: 20, ituZone: 39, continent: "AS"),
        "OE":       DXCCEntity(prefix: "OE",       country: "Austria",             cqZone: 15, ituZone: 28, continent: "EU"),
        "OH":       DXCCEntity(prefix: "OH",       country: "Finland",            cqZone: 15, ituZone: 18, continent: "EU"),
        "OH0":      DXCCEntity(prefix: "OH0",      country: "Finland (Aland Is.)", cqZone: 15, ituZone: 18, continent: "EU"),
        "OJ":       DXCCEntity(prefix: "OJ",       country: "Finland",             cqZone: 15, ituZone: 18, continent: "EU"),
        "OK":       DXCCEntity(prefix: "OK",       country: "Czech Republic",      cqZone: 15, ituZone: 28, continent: "EU"),
        "OM":       DXCCEntity(prefix: "OM",       country: "Slovakia",            cqZone: 15, ituZone: 28, continent: "EU"),
        "ON":       DXCCEntity(prefix: "ON",       country: "Belgium",             cqZone: 27, ituZone: 27, continent: "EU"),
        "OR":       DXCCEntity(prefix: "OR",       country: "Belgium",             cqZone: 27, ituZone: 27, continent: "EU"),
        "OS":       DXCCEntity(prefix: "OS",       country: "Belgium",             cqZone: 27, ituZone: 27, continent: "EU"),
        "OT":       DXCCEntity(prefix: "OT",       country: "Belgium",             cqZone: 27, ituZone: 27, continent: "EU"),
        "OU":       DXCCEntity(prefix: "OU",       country: "Denmark",             cqZone: 14, ituZone: 18, continent: "EU"),
        "OZ":       DXCCEntity(prefix: "OZ",       country: "Denmark (Greenland)", cqZone: 40, ituZone: 5,  continent: "NA"),
        "PA":       DXCCEntity(prefix: "PA",       country: "Netherlands",         cqZone: 14, ituZone: 27, continent: "EU"),
        "PB":       DXCCEntity(prefix: "PB",       country: "Netherlands",         cqZone: 14, ituZone: 27, continent: "EU"),
        "PC":       DXCCEntity(prefix: "PC",       country: "Netherlands",         cqZone: 14, ituZone: 27, continent: "EU"),
        "PD":       DXCCEntity(prefix: "PD",       country: "Netherlands",         cqZone: 14, ituZone: 27, continent: "EU"),
        "PE":       DXCCEntity(prefix: "PE",       country: "Netherlands",         cqZone: 14, ituZone: 27, continent: "EU"),
        "PF":       DXCCEntity(prefix: "PF",       country: "Netherlands",         cqZone: 14, ituZone: 27, continent: "EU"),
        "PG":       DXCCEntity(prefix: "PG",       country: "Netherlands",         cqZone: 14, ituZone: 27, continent: "EU"),
        "PH":       DXCCEntity(prefix: "PH",       country: "Netherlands",         cqZone: 14, ituZone: 27, continent: "EU"),
        "PI":       DXCCEntity(prefix: "PI",       country: "Netherlands",         cqZone: 14, ituZone: 27, continent: "EU"),
        "PJ":       DXCCEntity(prefix: "PJ",       country: "Netherlands (Curacao)", cqZone: 9, ituZone: 11, continent: "SA"),
        "PK":       DXCCEntity(prefix: "PK",       country: "Indonesia",          cqZone: 28, ituZone: 54, continent: "AS"),
        "PL":       DXCCEntity(prefix: "PL",       country: "Poland",             cqZone: 15, ituZone: 28, continent: "EU"),
        "PM":       DXCCEntity(prefix: "PM",       country: "Portugal",           cqZone: 14, ituZone: 37, continent: "EU"),
        "PN":       DXCCEntity(prefix: "PN",       country: "Portugal",           cqZone: 14, ituZone: 37, continent: "EU"),
        "PP":       DXCCEntity(prefix: "PP",       country: "Brazil",             cqZone: 11, ituZone: 15, continent: "SA"),
        "PQ":       DXCCEntity(prefix: "PQ",       country: "Brazil",             cqZone: 11, ituZone: 15, continent: "SA"),
        "PR":       DXCCEntity(prefix: "PR",       country: "Brazil",             cqZone: 11, ituZone: 15, continent: "SA"),
        "PS":       DXCCEntity(prefix: "PS",       country: "Brazil",             cqZone: 11, ituZone: 15, continent: "SA"),
        "PT":       DXCCEntity(prefix: "PT",       country: "Brazil",             cqZone: 11, ituZone: 15, continent: "SA"),
        "PU":       DXCCEntity(prefix: "PU",       country: "Brazil",             cqZone: 11, ituZone: 15, continent: "SA"),
        "PV":       DXCCEntity(prefix: "PV",       country: "Brazil",             cqZone: 11, ituZone: 15, continent: "SA"),
        "PW":       DXCCEntity(prefix: "PW",       country: "Brazil",             cqZone: 11, ituZone: 15, continent: "SA"),
        "PX":       DXCCEntity(prefix: "PX",       country: "Brazil",             cqZone: 11, ituZone: 15, continent: "SA"),
        "PY":       DXCCEntity(prefix: "PY",       country: "Brazil",             cqZone: 11, ituZone: 15, continent: "SA"),
        "PY0F":     DXCCEntity(prefix: "PY0F",     country: "Brazil (Fernando de Noronha)", cqZone: 11, ituZone: 13, continent: "SA"),
        "PY0S":     DXCCEntity(prefix: "PY0S",     country: "Brazil (Sao Pedro & Miquelon)", cqZone: 11, ituZone: 13, continent: "SA"),
        "PZ":       DXCCEntity(prefix: "PZ",       country: "Suriname",            cqZone: 9,  ituZone: 12, continent: "SA"),
        "RA":       DXCCEntity(prefix: "RA",       country: "Russia",             cqZone: nil, ituZone: nil, continent: "EU"),
        "RC":       DXCCEntity(prefix: "RC",       country: "Russia",             cqZone: nil, ituZone: nil, continent: "EU"),
        "RD":       DXCCEntity(prefix: "RD",       country: "Russia",             cqZone: nil, ituZone: nil, continent: "EU"),
        "RF":       DXCCEntity(prefix: "RF",       country: "Russia",             cqZone: nil, ituZone: nil, continent: "EU"),
        "RG":       DXCCEntity(prefix: "RG",       country: "Russia",             cqZone: nil, ituZone: nil, continent: "EU"),
        "RI":       DXCCEntity(prefix: "RI",       country: "Russia",             cqZone: nil, ituZone: nil, continent: "EU"),
        "RJ":       DXCCEntity(prefix: "RJ",       country: "Russia",             cqZone: nil, ituZone: nil, continent: "EU"),
        "RK":       DXCCEntity(prefix: "RK",       country: "Russia",             cqZone: nil, ituZone: nil, continent: "EU"),
        "RL":       DXCCEntity(prefix: "RL",       country: "Russia",             cqZone: nil, ituZone: nil, continent: "EU"),
        "RM":       DXCCEntity(prefix: "RM",       country: "Russia",             cqZone: nil, ituZone: nil, continent: "EU"),
        "RN":       DXCCEntity(prefix: "RN",       country: "Russia",             cqZone: nil, ituZone: nil, continent: "EU"),
        "RO":       DXCCEntity(prefix: "RO",       country: "Russia",             cqZone: nil, ituZone: nil, continent: "EU"),
        "RP":       DXCCEntity(prefix: "RP",       country: "Russia",             cqZone: nil, ituZone: nil, continent: "EU"),
        "RQ":       DXCCEntity(prefix: "RQ",       country: "Russia",             cqZone: nil, ituZone: nil, continent: "EU"),
        "RR":       DXCCEntity(prefix: "RR",       country: "Russia",             cqZone: nil, ituZone: nil, continent: "EU"),
        "RS":       DXCCEntity(prefix: "RS",       country: "Russia",             cqZone: nil, ituZone: nil, continent: "EU"),
        "RT":       DXCCEntity(prefix: "RT",       country: "Russia",             cqZone: nil, ituZone: nil, continent: "EU"),
        "RU":       DXCCEntity(prefix: "RU",       country: "Russia",             cqZone: nil, ituZone: nil, continent: "EU"),
        "RV":       DXCCEntity(prefix: "RV",       country: "Russia",             cqZone: nil, ituZone: nil, continent: "EU"),
        "RW":       DXCCEntity(prefix: "RW",       country: "Russia",             cqZone: nil, ituZone: nil, continent: "EU"),
        "RX":       DXCCEntity(prefix: "RX",       country: "Russia",             cqZone: nil, ituZone: nil, continent: "EU"),
        "RY":       DXCCEntity(prefix: "RY",       country: "Russia",             cqZone: nil, ituZone: nil, continent: "EU"),
        "RZ":       DXCCEntity(prefix: "RZ",       country: "Russia",             cqZone: nil, ituZone: nil, continent: "EU"),
        "UA":       DXCCEntity(prefix: "UA",       country: "Russia (European)",   cqZone: 16, ituZone: 29, continent: "EU"),
        "UA0":      DXCCEntity(prefix: "UA0",      country: "Russia (Siberia)",    cqZone: 17, ituZone: 18, continent: "AS"),
        "UA9":      DXCCEntity(prefix: "UA9",      country: "Russia (Asiatic)",    cqZone: 17, ituZone: 18, continent: "AS"),
        "UB":       DXCCEntity(prefix: "UB",       country: "Ukraine",            cqZone: 16, ituZone: 29, continent: "EU"),
        "UC":       DXCCEntity(prefix: "UC",       country: "Ukraine",            cqZone: 16, ituZone: 29, continent: "EU"),
        "UD":       DXCCEntity(prefix: "UD",       country: "Ukraine",            cqZone: 16, ituZone: 29, continent: "EU"),
        "UE":       DXCCEntity(prefix: "UE",       country: "Ukraine",            cqZone: 16, ituZone: 29, continent: "EU"),
        "UF":       DXCCEntity(prefix: "UF",       country: "Ukraine",            cqZone: 16, ituZone: 29, continent: "EU"),
        "UG":       DXCCEntity(prefix: "UG",       country: "Ukraine",            cqZone: 16, ituZone: 29, continent: "EU"),
        "UH":       DXCCEntity(prefix: "UH",       country: "Russia",             cqZone: 17, ituZone: 30, continent: "AS"),
        "UI":       DXCCEntity(prefix: "UI",       country: "Russia",             cqZone: 17, ituZone: 30, continent: "AS"),
        "UJ":       DXCCEntity(prefix: "UJ",       country: "Uzbekistan",          cqZone: 17, ituZone: 30, continent: "AS"),
        "UN":       DXCCEntity(prefix: "UN",       country: "Kazakhstan",         cqZone: 17, ituZone: 30, continent: "AS"),
        "UO":       DXCCEntity(prefix: "UO",       country: "Romania",            cqZone: 20, ituZone: 28, continent: "EU"),
        "UR":       DXCCEntity(prefix: "UR",       country: "Ukraine",            cqZone: 16, ituZone: 29, continent: "EU"),
        "UT":       DXCCEntity(prefix: "UT",       country: "Ukraine",            cqZone: 16, ituZone: 29, continent: "EU"),
        "UU":       DXCCEntity(prefix: "UU",       country: "Ukraine",            cqZone: 16, ituZone: 29, continent: "EU"),
        "UV":       DXCCEntity(prefix: "UV",       country: "Ukraine",            cqZone: 16, ituZone: 29, continent: "EU"),
        "UW":       DXCCEntity(prefix: "UW",       country: "Ukraine",            cqZone: 16, ituZone: 29, continent: "EU"),
        "UX":       DXCCEntity(prefix: "UX",       country: "Ukraine",            cqZone: 16, ituZone: 29, continent: "EU"),
        "UY":       DXCCEntity(prefix: "UY",       country: "Ukraine",            cqZone: 16, ituZone: 29, continent: "EU"),
        "UZ":       DXCCEntity(prefix: "UZ",       country: "Ukraine",            cqZone: 16, ituZone: 29, continent: "EU"),

        // ── Western Europe ─────────────────────────────────
        "DA-DL":    DXCCEntity(prefix: "DA-DL",   country: "Germany",             cqZone: 14, ituZone: 28, continent: "EU"),
        "Y2-Y9":    DXCCEntity(prefix: "Y2-Y9",   country: "Germany",             cqZone: 14, ituZone: 28, continent: "EU"),
        "EA-EH":    DXCCEntity(prefix: "EA-EH",   country: "Spain",               cqZone: 14, ituZone: 37, continent: "EU"),
        "EB-EJ":    DXCCEntity(prefix: "EB-EJ",   country: "Spain",              cqZone: 14, ituZone: 37, continent: "EU"),
        "F":        DXCCEntity(prefix: "F",        country: "France",              cqZone: 14, ituZone: 27, continent: "EU"),
        "HW-HY":    DXCCEntity(prefix: "HW-HY",   country: "France",              cqZone: 14, ituZone: 27, continent: "EU"),
        "TH":       DXCCEntity(prefix: "TH",       country: "France",              cqZone: 14, ituZone: 27, continent: "EU"),
        "TK":       DXCCEntity(prefix: "TK",       country: "France (Corsica)",    cqZone: 14, ituZone: 27, continent: "EU"),
        "TM":       DXCCEntity(prefix: "TM",       country: "France",              cqZone: 14, ituZone: 27, continent: "EU"),
        "G":        DXCCEntity(prefix: "G",        country: "United Kingdom",     cqZone: 14, ituZone: 27, continent: "EU"),
        "GD":       DXCCEntity(prefix: "GD",       country: "Isle of Man",         cqZone: 14, ituZone: 27, continent: "EU"),
        "GI":       DXCCEntity(prefix: "GI",       country: "Northern Ireland",    cqZone: 14, ituZone: 27, continent: "EU"),
        "GJ":       DXCCEntity(prefix: "GJ",       country: "Jersey",              cqZone: 14, ituZone: 27, continent: "EU"),
        "GM":       DXCCEntity(prefix: "GM",       country: "Scotland",            cqZone: 14, ituZone: 27, continent: "EU"),
        "GN":       DXCCEntity(prefix: "GN",       country: "Scotland (Shetland)", cqZone: 14, ituZone: 27, continent: "EU"),
        "GP":       DXCCEntity(prefix: "GP",       country: "Guernsey",             cqZone: 14, ituZone: 27, continent: "EU"),
        "GS":       DXCCEntity(prefix: "GS",       country: "Scotland",            cqZone: 14, ituZone: 27, continent: "EU"),
        "GW":       DXCCEntity(prefix: "GW",       country: "Wales",              cqZone: 14, ituZone: 27, continent: "EU"),
        "HA":       DXCCEntity(prefix: "HA",       country: "Hungary",             cqZone: 15, ituZone: 28, continent: "EU"),
        "HB":       DXCCEntity(prefix: "HB",       country: "Switzerland",         cqZone: 14, ituZone: 28, continent: "EU"),
        "HB0":      DXCCEntity(prefix: "HB0",      country: "Liechtenstein",       cqZone: 14, ituZone: 28, continent: "EU"),
        "HC-HD":    DXCCEntity(prefix: "HC-HD",   country: "Ecuador",             cqZone: 10, ituZone: 12, continent: "SA"),
        "HE":       DXCCEntity(prefix: "HE",       country: "Switzerland",         cqZone: 14, ituZone: 28, continent: "EU"),
        "HG":       DXCCEntity(prefix: "HG",       country: "Hungary",             cqZone: 15, ituZone: 28, continent: "EU"),
        "HL":       DXCCEntity(prefix: "HL",       country: "South Korea",        cqZone: 25, ituZone: 44, continent: "AS"),
        "HM":       DXCCEntity(prefix: "HM",       country: "North Korea",         cqZone: 25, ituZone: 44, continent: "AS"),
        "HO":       DXCCEntity(prefix: "HO",       country: "Panama",              cqZone: 7,  ituZone: 11, continent: "NA"),
        "HP":       DXCCEntity(prefix: "HP",       country: "Panama",              cqZone: 7,  ituZone: 11, continent: "NA"),
        "HQ":       DXCCEntity(prefix: "HQ",       country: "Honduras",            cqZone: 7,  ituZone: 11, continent: "NA"),
        "HR":       DXCCEntity(prefix: "HR",       country: "Honduras",            cqZone: 7,  ituZone: 11, continent: "NA"),
        "HS":       DXCCEntity(prefix: "HS",       country: "Thailand",            cqZone: 26, ituZone: 49, continent: "AS"),
        "HV":       DXCCEntity(prefix: "HV",       country: "Vatican",            cqZone: 15, ituZone: 28, continent: "EU"),
        "HZ":       DXCCEntity(prefix: "HZ",       country: "Saudi Arabia",        cqZone: 21, ituZone: 39, continent: "AS"),
        "I":        DXCCEntity(prefix: "I",        country: "Italy",               cqZone: 15, ituZone: 28, continent: "EU"),
        "IG":       DXCCEntity(prefix: "IG",       country: "Italy (Sardinia)",    cqZone: 15, ituZone: 28, continent: "EU"),
        "IS":       DXCCEntity(prefix: "IS",       country: "Italy (Sicily)",      cqZone: 15, ituZone: 28, continent: "EU"),
        "J":        DXCCEntity(prefix: "J",        country: "Japan",               cqZone: 25, ituZone: 45, continent: "AS"),
        "JA-JS":    DXCCEntity(prefix: "JA-JS",   country: "Japan",               cqZone: 25, ituZone: 45, continent: "AS"),
        "JD":       DXCCEntity(prefix: "JD",       country: "Japan (Minami Torishima)", cqZone: 25, ituZone: 90, continent: "AS"),
        "JE":       DXCCEntity(prefix: "JE",       country: "Japan",               cqZone: 25, ituZone: 45, continent: "AS"),
        "JF":       DXCCEntity(prefix: "JF",       country: "Japan",               cqZone: 25, ituZone: 45, continent: "AS"),
        "JG":       DXCCEntity(prefix: "JG",       country: "Japan",               cqZone: 25, ituZone: 45, continent: "AS"),
        "JH":       DXCCEntity(prefix: "JH",       country: "Japan",               cqZone: 25, ituZone: 45, continent: "AS"),
        "JI":       DXCCEntity(prefix: "JI",       country: "Japan",               cqZone: 25, ituZone: 45, continent: "AS"),
        "JJ":       DXCCEntity(prefix: "JJ",       country: "Japan",               cqZone: 25, ituZone: 45, continent: "AS"),
        "JK":       DXCCEntity(prefix: "JK",       country: "Japan",               cqZone: 25, ituZone: 45, continent: "AS"),
        "JL":       DXCCEntity(prefix: "JL",       country: "Japan",               cqZone: 25, ituZone: 45, continent: "AS"),
        "JM":       DXCCEntity(prefix: "JM",       country: "Japan",               cqZone: 25, ituZone: 45, continent: "AS"),
        "JN":       DXCCEntity(prefix: "JN",       country: "Japan",               cqZone: 25, ituZone: 45, continent: "AS"),
        "JO":       DXCCEntity(prefix: "JO",       country: "Japan",               cqZone: 25, ituZone: 45, continent: "AS"),
        "JP":       DXCCEntity(prefix: "JP",       country: "Japan",               cqZone: 25, ituZone: 45, continent: "AS"),
        "JQ":       DXCCEntity(prefix: "JQ",       country: "Japan",               cqZone: 25, ituZone: 45, continent: "AS"),
        "JR":       DXCCEntity(prefix: "JR",       country: "Japan",               cqZone: 25, ituZone: 45, continent: "AS"),
        "JS":       DXCCEntity(prefix: "JS",       country: "Japan",               cqZone: 25, ituZone: 45, continent: "AS"),
        "JT":       DXCCEntity(prefix: "JT",       country: "Mongolia",            cqZone: 23, ituZone: 46, continent: "AS"),
        "JV":       DXCCEntity(prefix: "JV",       country: "Mongolia",            cqZone: 23, ituZone: 46, continent: "AS"),
        "JX":       DXCCEntity(prefix: "JX",       country: "Norway (Svalbard)",   cqZone: 40, ituZone: 18, continent: "EU"),
        "JY":       DXCCEntity(prefix: "JY",       country: "Jordan",              cqZone: 20, ituZone: 39, continent: "AS"),
        "LA-LN":    DXCCEntity(prefix: "LA-LN",   country: "Norway",               cqZone: 14, ituZone: 18, continent: "EU"),
        "LO-LW":    DXCCEntity(prefix: "LO-LW",   country: "Argentina",           cqZone: 13, ituZone: 14, continent: "SA"),
        "MA-MZ":    DXCCEntity(prefix: "MA-MZ",   country: "Spain (Ceuta/Melilla)", cqZone: 33, ituZone: 37, continent: "AF"),
        "MC-MJ":    DXCCEntity(prefix: "MC-MJ",   country: "Spain",               cqZone: 14, ituZone: 37, continent: "EU"),
        "MK":       DXCCEntity(prefix: "MK",       country: "Scotland",            cqZone: 14, ituZone: 27, continent: "EU"),
        "MM":       DXCCEntity(prefix: "MM",       country: "Scotland",            cqZone: 14, ituZone: 27, continent: "EU"),
        "MN":       DXCCEntity(prefix: "MN",       country: "Scotland (Shetland)", cqZone: 14, ituZone: 27, continent: "EU"),
        "MP":       DXCCEntity(prefix: "MP",       country: "Guernsey",             cqZone: 14, ituZone: 27, continent: "EU"),
        "MQ":       DXCCEntity(prefix: "MQ",       country: "Jersey",              cqZone: 14, ituZone: 27, continent: "EU"),
        "MR":       DXCCEntity(prefix: "MR",       country: "Isle of Man",         cqZone: 14, ituZone: 27, continent: "EU"),
        "MS":       DXCCEntity(prefix: "MS",       country: "Wales",              cqZone: 14, ituZone: 27, continent: "EU"),
        "MT":       DXCCEntity(prefix: "MT",       country: "Northern Ireland",    cqZone: 14, ituZone: 27, continent: "EU"),
        "MU":       DXCCEntity(prefix: "MU",       country: "England",             cqZone: 14, ituZone: 27, continent: "EU"),
        "MW":       DXCCEntity(prefix: "MW",       country: "Wales",              cqZone: 14, ituZone: 27, continent: "EU"),
        "MX":       DXCCEntity(prefix: "MX",       country: "England",             cqZone: 14, ituZone: 27, continent: "EU"),
        "MY":       DXCCEntity(prefix: "MY",       country: "England",             cqZone: 14, ituZone: 27, continent: "EU"),
        "MZ":       DXCCEntity(prefix: "MZ",       country: "England",             cqZone: 14, ituZone: 27, continent: "EU"),
        "E":        DXCCEntity(prefix: "E",        country: "Spain",               cqZone: 14, ituZone: 37, continent: "EU"),
        "EA6-EA9":  DXCCEntity(prefix: "EA6-EA9", country: "Spain (Balearic/Canary)", cqZone: 14, ituZone: 37, continent: "EU"),
        "EH1-EH9":  DXCCEntity(prefix: "EH1-EH9", country: "Spain",               cqZone: 14, ituZone: 37, continent: "EU"),
        "ER":       DXCCEntity(prefix: "ER",       country: "Moldova",            cqZone: 16, ituZone: 29, continent: "EU"),
        "ES":       DXCCEntity(prefix: "ES",       country: "Estonia",             cqZone: 15, ituZone: 29, continent: "EU"),
        "ET":       DXCCEntity(prefix: "ET",       country: "Ethiopia",            cqZone: 37, ituZone: 48, continent: "AF"),
        "EU-EW":    DXCCEntity(prefix: "EU-EW",   country: "Belarus",             cqZone: 16, ituZone: 29, continent: "EU"),
        "EY":       DXCCEntity(prefix: "EY",       country: "Tajikistan",         cqZone: 17, ituZone: 30, continent: "AS"),
        "EZ":       DXCCEntity(prefix: "EZ",       country: "Turkmenistan",        cqZone: 17, ituZone: 30, continent: "AS"),
        "SP-W":     DXCCEntity(prefix: "SP-W",    country: "Poland",              cqZone: 15, ituZone: 28, continent: "EU"),
        "SP":       DXCCEntity(prefix: "SP",       country: "Poland",              cqZone: 15, ituZone: 28, continent: "EU"),
        "SQ":       DXCCEntity(prefix: "SQ",       country: "Poland",              cqZone: 15, ituZone: 28, continent: "EU"),
        "3A":       DXCCEntity(prefix: "3A",       country: "Monaco",              cqZone: 14, ituZone: 27, continent: "EU"),
        "3B":       DXCCEntity(prefix: "3B",       country: "Mauritius",           cqZone: 39, ituZone: 53, continent: "AF"),
        "3B6":      DXCCEntity(prefix: "3B6",      country: "Seychelles (Farquhar)", cqZone: 39, ituZone: 53, continent: "AF"),
        "3B7":      DXCCEntity(prefix: "3B7",      country: "Seychelles (Agalega)", cqZone: 39, ituZone: 53, continent: "AF"),
        "3B8":      DXCCEntity(prefix: "3B8",      country: "Mauritius",           cqZone: 39, ituZone: 53, continent: "AF"),
        "3B9":      DXCCEntity(prefix: "3B9",      country: "Mauritius (Rodriguez)", cqZone: 39, ituZone: 53, continent: "AF"),
        "3C":       DXCCEntity(prefix: "3C",       country: "Equatorial Guinea",   cqZone: 36, ituZone: 47, continent: "AF"),
        "3C0":      DXCCEntity(prefix: "3C0",      country: "Equatorial Guinea (Annobon)", cqZone: 36, ituZone: 47, continent: "AF"),
        "3D2":      DXCCEntity(prefix: "3D2",      country: "Fiji",                cqZone: 32, ituZone: 56, continent: "OC"),
        "3D2R":     DXCCEntity(prefix: "3D2R",     country: "Fiji (Rotuma)",       cqZone: 32, ituZone: 56, continent: "OC"),
        "3DA":      DXCCEntity(prefix: "3DA",      country: "Eswatini",            cqZone: 38, ituZone: 57, continent: "AF"),
        "3V":       DXCCEntity(prefix: "3V",       country: "Tunisia",             cqZone: 33, ituZone: 37, continent: "AF"),
        "3W":       DXCCEntity(prefix: "3W",       country: "Vietnam",             cqZone: 26, ituZone: 49, continent: "AS"),
        "3X":       DXCCEntity(prefix: "3X",       country: "Guinea",              cqZone: 35, ituZone: 46, continent: "AF"),
        "3Y":       DXCCEntity(prefix: "3Y",       country: "Norway (Bouvet)",     cqZone: 38, ituZone: 29, continent: "AF"),
        "3Z":       DXCCEntity(prefix: "3Z",       country: "Poland",              cqZone: 15, ituZone: 28, continent: "EU"),
        "4J":       DXCCEntity(prefix: "4J",       country: "Azerbaijan",          cqZone: 21, ituZone: 29, continent: "AS"),
        "4K":       DXCCEntity(prefix: "4K",       country: "Azerbaijan",          cqZone: 21, ituZone: 29, continent: "AS"),
        "4L":       DXCCEntity(prefix: "4L",       country: "Georgia",             cqZone: 21, ituZone: 29, continent: "AS"),
        "4S":       DXCCEntity(prefix: "4S",       country: "Sri Lanka",           cqZone: 22, ituZone: 41, continent: "AS"),
        "4U":       DXCCEntity(prefix: "4U",       country: "United Nations HQ",   cqZone: 8,  ituZone: 8,  continent: "NA"),
        "4U1":      DXCCEntity(prefix: "4U1",      country: "United Nations HQ",   cqZone: 8,  ituZone: 8,  continent: "NA"),
        "4V":       DXCCEntity(prefix: "4V",       country: "Haiti",                cqZone: 8,  ituZone: 20, continent: "NA"),
        "4W":       DXCCEntity(prefix: "4W",       country: "Timor-Leste",         cqZone: 28, ituZone: 54, continent: "OC"),
        "4X":       DXCCEntity(prefix: "4X",       country: "Israel",              cqZone: 20, ituZone: 39, continent: "AS"),
        "4Z":       DXCCEntity(prefix: "4Z",       country: "Israel",              cqZone: 20, ituZone: 39, continent: "AS"),
        "5A":       DXCCEntity(prefix: "5A",       country: "Libya",               cqZone: 34, ituZone: 38, continent: "AF"),
        "5B":       DXCCEntity(prefix: "5B",       country: "Cyprus",              cqZone: 20, ituZone: 39, continent: "EU"),
        "5H":       DXCCEntity(prefix: "5H",       country: "Tanzania",            cqZone: 37, ituZone: 48, continent: "AF"),
        "5N":       DXCCEntity(prefix: "5N",       country: "Nigeria",             cqZone: 35, ituZone: 46, continent: "AF"),
        "5R":       DXCCEntity(prefix: "5R",       country: "Madagascar",          cqZone: 39, ituZone: 53, continent: "AF"),
        "5T":       DXCCEntity(prefix: "5T",       country: "Mauritania",          cqZone: 35, ituZone: 46, continent: "AF"),
        "5U":       DXCCEntity(prefix: "5U",       country: "Niger",               cqZone: 35, ituZone: 46, continent: "AF"),
        "5V":       DXCCEntity(prefix: "5V",       country: "Togo",                cqZone: 35, ituZone: 46, continent: "AF"),
        "5W":       DXCCEntity(prefix: "5W",       country: "Samoa",               cqZone: 32, ituZone: 62, continent: "OC"),
        "5X":       DXCCEntity(prefix: "5X",       country: "Uganda",              cqZone: 37, ituZone: 48, continent: "AF"),
        "5Y":       DXCCEntity(prefix: "5Y",       country: "Kenya",               cqZone: 37, ituZone: 48, continent: "AF"),
        "5Z":       DXCCEntity(prefix: "5Z",       country: "Kenya",               cqZone: 37, ituZone: 48, continent: "AF"),
        "6W":       DXCCEntity(prefix: "6W",       country: "Senegal",             cqZone: 35, ituZone: 46, continent: "AF"),
        "6Y":       DXCCEntity(prefix: "6Y",       country: "Jamaica",              cqZone: 8,  ituZone: 11, continent: "NA"),
        "6Z":       DXCCEntity(prefix: "6Z",       country: "Liberia",              cqZone: 35, ituZone: 46, continent: "AF"),
        "7O":       DXCCEntity(prefix: "7O",       country: "Yemen",               cqZone: 21, ituZone: 39, continent: "AS"),
        "7P":       DXCCEntity(prefix: "7P",       country: "Lesotho",             cqZone: 38, ituZone: 57, continent: "AF"),
        "7Q":       DXCCEntity(prefix: "7Q",       country: "Malawi",              cqZone: 37, ituZone: 53, continent: "AF"),
        "7T":       DXCCEntity(prefix: "7T",       country: "Algeria",             cqZone: 33, ituZone: 37, continent: "AF"),
        "7U":       DXCCEntity(prefix: "7U",       country: "Algeria",             cqZone: 33, ituZone: 37, continent: "AF"),
        "7V":       DXCCEntity(prefix: "7V",       country: "Algeria",             cqZone: 33, ituZone: 37, continent: "AF"),
        "7W":       DXCCEntity(prefix: "7W",       country: "Algeria",             cqZone: 33, ituZone: 37, continent: "AF"),
        "7X":       DXCCEntity(prefix: "7X",       country: "Algeria",             cqZone: 33, ituZone: 37, continent: "AF"),
        "7Y":       DXCCEntity(prefix: "7Y",       country: "Algeria",             cqZone: 33, ituZone: 37, continent: "AF"),
        "8J":       DXCCEntity(prefix: "8J",       country: "Japan",               cqZone: 25, ituZone: 45, continent: "AS"),
        "8N":       DXCCEntity(prefix: "8N",       country: "Japan",               cqZone: 25, ituZone: 45, continent: "AS"),
        "8P":       DXCCEntity(prefix: "8P",       country: "Barbados",             cqZone: 8,  ituZone: 11, continent: "NA"),
        "8Q":       DXCCEntity(prefix: "8Q",       country: "Maldives",            cqZone: 22, ituZone: 41, continent: "AS"),
        "8R":       DXCCEntity(prefix: "8R",       country: "Guyana",              cqZone: 9,  ituZone: 12, continent: "SA"),
        "8T":       DXCCEntity(prefix: "8T",       country: "India",               cqZone: 22, ituZone: 41, continent: "AS"),
        "8U":       DXCCEntity(prefix: "8U",       country: "India",               cqZone: 22, ituZone: 41, continent: "AS"),
        "8V":       DXCCEntity(prefix: "8V",       country: "India",               cqZone: 22, ituZone: 41, continent: "AS"),
        "8W":       DXCCEntity(prefix: "8W",       country: "India",               cqZone: 22, ituZone: 41, continent: "AS"),
        "8X":       DXCCEntity(prefix: "8X",       country: "India",               cqZone: 22, ituZone: 41, continent: "AS"),
        "8Y":       DXCCEntity(prefix: "8Y",       country: "India",               cqZone: 22, ituZone: 41, continent: "AS"),
        "8Z":       DXCCEntity(prefix: "8Z",       country: "India",               cqZone: 22, ituZone: 41, continent: "AS"),
        "9A":       DXCCEntity(prefix: "9A",       country: "Croatia",             cqZone: 15, ituZone: 28, continent: "EU"),
        "9G":       DXCCEntity(prefix: "9G",       country: "Ghana",                cqZone: 35, ituZone: 46, continent: "AF"),
        "9H":       DXCCEntity(prefix: "9H",       country: "Malta",                cqZone: 15, ituZone: 28, continent: "EU"),
        "9J":       DXCCEntity(prefix: "9J",       country: "Zambia",              cqZone: 36, ituZone: 53, continent: "AF"),
        "9K":       DXCCEntity(prefix: "9K",       country: "Kuwait",              cqZone: 21, ituZone: 39, continent: "AS"),
        "9L":       DXCCEntity(prefix: "9L",       country: "Sierra Leone",         cqZone: 35, ituZone: 46, continent: "AF"),
        "9M":       DXCCEntity(prefix: "9M",       country: "Malaysia",             cqZone: 28, ituZone: 54, continent: "AS"),
        "9M2":      DXCCEntity(prefix: "9M2",      country: "Malaysia (West)",     cqZone: 28, ituZone: 54, continent: "AS"),
        "9M6":      DXCCEntity(prefix: "9M6",      country: "Malaysia (East)",      cqZone: 28, ituZone: 54, continent: "AS"),
        "9N":       DXCCEntity(prefix: "9N",       country: "Nepal",                cqZone: 22, ituZone: 42, continent: "AS"),
        "9Q":       DXCCEntity(prefix: "9Q",       country: "DR Congo",             cqZone: 36, ituZone: 52, continent: "AF"),
        "9S":       DXCCEntity(prefix: "9S",       country: "South Sudan",         cqZone: 36, ituZone: 48, continent: "AF"),
        "9T":       DXCCEntity(prefix: "9T",       country: "DR Congo",             cqZone: 36, ituZone: 52, continent: "AF"),
        "9U":       DXCCEntity(prefix: "9U",       country: "Burundi",              cqZone: 36, ituZone: 52, continent: "AF"),
        "9V":       DXCCEntity(prefix: "9V",       country: "Singapore",            cqZone: 28, ituZone: 54, continent: "AS"),
        "9X":       DXCCEntity(prefix: "9X",       country: "Rwanda",              cqZone: 36, ituZone: 52, continent: "AF"),
        "9Y":       DXCCEntity(prefix: "9Y",       country: "Trinidad & Tobago",   cqZone: 9,  ituZone: 11, continent: "SA"),
        "9Z":       DXCCEntity(prefix: "9Z",       country: "Trinidad & Tobago",   cqZone: 9,  ituZone: 11, continent: "SA"),
    ]

    // ── Lookup ─────────────────────────────────────────────────

    /// Longest-prefix match — e.g. "K1ABC" → "United States"
    func lookup(callsign: String) -> DXCCEntity? {
        let upper = callsign.uppercased()

        // Try up to 5 leading characters for prefix match
        for len in stride(from: min(5, upper.count), through: 1, by: -1) {
            let prefix = String(upper.prefix(len))
            if let entity = entities[prefix] {
                return entity
            }
            // Also try with suffix (e.g. "4U" for "4U1ITU")
            if let entity = entities[prefix + "-"] {
                return entity
            }
        }
        return nil
    }

    /// All unique countries from a list of QSOs
    func uniqueCountries(from qsos: [QSO]) -> [DXCCEntity] {
        var seen = Set<String>()
        var result: [DXCCEntity] = []
        for qso in qsos {
            if let entity = lookup(callsign: qso.callsign),
               !seen.contains(entity.country) {
                seen.insert(entity.country)
                result.append(entity)
            }
        }
        return result.sorted { $0.country < $1.country }
    }
}
