default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: "DN4FWLF924",
      issuer_id: "69a6de6e-b923-47e3-e053-5b8c7c11a4d1",
      key_filepath: File.expand_path("~/.appstoreconnect/private_keys/AuthKey_DN4FWLF924.p8")
    )

    sigh(
      api_key: api_key,
      app_identifier: "com.stephenthorn.HAMSignal",
      team_id: "TXHUY489RV",
    )

    gym(
      scheme: "HAMAllInOne",
      project: "HAMAllInOne.xcodeproj",
      configuration: "Release",
      export_method: "app-store",
      export_options: {
        teamID: "TXHUY489RV",
        signingStyle: "automatic",
        uploadBitcode: false,
        uploadSymbols: true,
      },
      output_directory: "/tmp/hamall-build",
      output_name: "HAMAllInOne.ipa",
      clean: true,
    )

    pilot(
      api_key: api_key,
      skip_waiting_for_build_processing: true,
      app_identifier: "com.stephenthorn.HAMSignal"
    )
  end
end
